spring.application.name=file-upload-system


# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_knowledge_assistant
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# ===============================
# SQL LOGGING
# ===============================

# Show SQL Queries
logging.level.org.hibernate.SQL=DEBUG

# Show Query Parameters
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Show JDBC Operations
logging.level.org.springframework.jdbc.core=DEBUG

# ===============================
# TURN OFF NOISY LOGS
# ===============================

logging.level.org.hibernate.stat=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# FILE UPLOAD (future use)
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# JWT CONFIGURATION
# ===============================

jwt.secret=MySuperSecretKeyForJwtAuthenticationInSpringBoot2026AndVeryLongSecretKey123456789
jwt.expiration=86400000


# ===============================
# DOCUMENT STORAGE
# ===============================
document.upload-dir=uploads

# ===============================
# CHUNK SIZES AND OVERLAP SIZE
# ===============================
chunk.size=300
chunk.overlap=50


# ===============================
# OLLAMA CONFIGURATION
# ===============================

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.ollama.chat.options.model=llama3.2

# ===============================
# GEMINI CONFIGURATION
# ===============================

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.options.model=gemini-3.5-flash

spring.ai.google.genai.embedding.text.model=gemini-embedding-001

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}

spring.ai.model.embedding.text=google-genai

# ===============================
# Retrieval Limit
# ===============================

retrieval.top-k=5

#----------DB Diagram--------------

#https://dbdiagram.io/d/6a366b7f5c789b8acbc4f297